kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
  namespace: messaging
  labels:
    app: rabbitmq
spec:
  clusterIP: None
  ports:
    - name: 15671-tcp
      protocol: TCP
      port: 15671
      targetPort: 15671
    - name: 15672-tcp
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: 15691-tcp
      protocol: TCP
      port: 15691
      targetPort: 15691
    - name: 15692-tcp
      protocol: TCP
      port: 15692
      targetPort: 15692
    - name: 25672-tcp
      protocol: TCP
      port: 25672
      targetPort: 25672
    - name: 4369-tcp
      protocol: TCP
      port: 4369
      targetPort: 4369
    - name: 5671-tcp
      protocol: TCP
      port: 5671
      targetPort: 5671
    - name: 5672-tcp
      protocol: TCP
      port: 5672
      targetPort: 5672
  type: ClusterIP
  selector:
    app: rabbitmq
