apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sample
  name: masstransit-webapi
  labels:
    app: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: masstransit-webapi
  template:
    metadata:
      labels:
        app: masstransit-webapi
    spec:
      containers:
        - image: mrstefangrimm/masstransit-webapi:0.8
          name: masstransit-webapi
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: kubernetes
          resources: {}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: webapi-appsettings-config
