apiVersion: v1
kind: Service
metadata:
  labels:
    run: webapi
  name: webapi
  namespace: sample
spec:
  ports:
    - name: swaggergateway
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: masstransit-webapi
  type: LoadBalancer
